# Generated by Django 4.1.2 on 2022-11-01 06:32

import datetimeutc.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_auto_added', datetimeutc.fields.DateTimeUTCField(auto_now_add=True)),
                ('time_auto_updated', datetimeutc.fields.DateTimeUTCField(auto_now=True)),
                ('time_set_manually', datetimeutc.fields.DateTimeUTCField(null=True)),
            ],
        ),
    ]
